.\"
.\" ----------------------------------------------------------------------------
.\" "THE BEER-WARE LICENSE" (Revision 42):
.\" <phk@login.dkuug.dk> wrote this file.  As long as you retain this notice you
.\" can do whatever you want with this stuff. If we meet some day, and you think
.\" this stuff is worth it, you can buy me a beer in return.   Poul-Henning Kamp
.\" ----------------------------------------------------------------------------
.\"
.\" 	$OpenBSD: md4.3,v 1.11 2010/07/13 22:34:45 tedu Exp $
.\"
.Dd $Mdocdate: July 13 2010 $
.Dt MD4 3
.Os
.Sh NAME
.Nm MD4Init ,
.Nm MD4Update ,
.Nm MD4Pad ,
.Nm MD4Final ,
.Nm MD4Transform ,
.Nm MD4End ,
.Nm MD4File ,
.Nm MD4FileChunk ,
.Nm MD4Data
.Nd calculate the RSA Data Security, Inc., ``MD4'' message digest
.Sh SYNOPSIS
.Fd #include <sys/types.h>
.Fd #include <md4.h>
.Ft void
.Fn MD4Init "MD4_CTX *context"
.Ft void
.Fn MD4Update "MD4_CTX *context" "const u_int8_t *data" "size_t len"
.Ft void
.Fn MD4Pad "MD4_CTX *context"
.Ft void
.Fn MD4Final "u_int8_t digest[MD4_DIGEST_LENGTH]" "MD4_CTX *context"
.Ft void
.Fn MD4Transform "u_int32_t state[4]" "u_int8_t block[MD4_BLOCK_LENGTH]"
.Ft "char *"
.Fn MD4End "MD4_CTX *context" "char *buf"
.Ft "char *"
.Fn MD4File "const char *filename" "char *buf"
.Ft "char *"
.Fn MD4FileChunk "const char *filename" "char *buf" "off_t offset" "off_t length"
.Ft "char *"
.Fn MD4Data "const u_int8_t *data" "size_t len" "char *buf"
.Sh DESCRIPTION
The MD4 functions calculate a 128-bit cryptographic checksum (digest)
for any number of input bytes.
A cryptographic checksum is a one-way
hash-function, that is, you cannot find (except by exhaustive search)
the input corresponding to a particular output.
This net result is a
.Dq fingerprint
of the input-data, which doesn't disclose the actual input.
.Pp
MD4 and MD5 have been broken; they should only be used where necessary for
backward compatibility.
The attacks on both MD4 and MD5
are both in the nature of finding
.Dq collisions
\- that is, multiple
inputs which hash to the same value; it is still unlikely for an attacker
to be able to determine the exact original input given a hash value.
.Pp
The
.Fn MD4Init ,
.Fn MD4Update ,
and
.Fn MD4Final
functions are the core functions.
Allocate an MD4_CTX, initialize it with
.Fn MD4Init ,
run over the data with
.Fn MD4Update ,
and finally extract the result using
.Fn MD4Final .
.Pp
The
.Fn MD4Pad
function can be used to apply padding to the message digest as in
.Fn MD4Final ,
but the current context can still be used with
.Fn MD4Update .
.Pp
The
.Fn MD4Transform
function is used by
.Fn MD4Update
to hash 512-bit blocks and forms the core of the algorithm.
Most programs should use the interface provided by
.Fn MD4Init ,
.Fn MD4Update
and
.Fn MD4Final
instead of calling
.Fn MD4Transform
directly.
.Pp
.Fn MD4End
is a wrapper for
.Fn MD4Final
which converts the return value to an MD4_DIGEST_STRING_LENGTH-character
(including the terminating '\e0')
.Tn ASCII
string which represents the 128 bits in hexadecimal.
.Pp
.Fn MD4File
calculates the digest of a file, and uses
.Fn MD4End
to return the result.
If the file cannot be opened, a null pointer is returned.
.Pp
.Fn MD4FileChunk
behaves like
.Fn MD4File
but calculates the digest only for that portion of the file starting at
.Fa offset
and continuing for
.Fa length
bytes or until end of file is reached, whichever comes first.
A zero
.Fa length
can be specified to read until end of file.
A negative
.Fa length
or
.Fa offset
will be ignored.
.Fn MD4Data
calculates the digest of a chunk of data in memory, and uses
.Fn MD4End
to return the result.
.Pp
When using
.Fn MD4End ,
.Fn MD4File ,
.Fn MD4FileChunk ,
or
.Fn MD4Data ,
the
.Ar buf
argument can be a null pointer, in which case the returned string
is allocated with
.Xr malloc 3
and subsequently must be explicitly deallocated using
.Xr free 3
after use.
If the
.Ar buf
argument is non-null it must point to at least MD4_DIGEST_STRING_LENGTH
characters of buffer space.
.Sh SEE ALSO
.Xr cksum 1 ,
.Xr md5 1 ,
.Xr md5 3 ,
.Xr rmd160 3 ,
.Xr sha1 3 ,
.Xr sha2 3
.Rs
.%A R. Rivest
.%T The MD4 Message-Digest Algorithm
.%O RFC 1186
.Re
.Rs
.%A R. Rivest
.%T The MD5 Message-Digest Algorithm
.%O RFC 1321
.Re
.Rs
.%A RSA Laboratories
.%T Frequently Asked Questions About today's Cryptography
.%O \&<http://www.rsa.com/rsalabs/faq/>
.Re
.Rs
.%A H. Dobbertin
.%T Alf Swindles Ann
.%J CryptoBytes
.%N 1(3):5
.%D 1995
.Re
.Rs
.%A MJ. B. Robshaw
.%T On Recent Results for MD4 and MD5
.%J RSA Laboratories Bulletin
.%N 4
.%D November 12, 1996
.Re
.Rs
.%A Hans Dobbertin
.%T Cryptanalysis of MD5 Compress
.Re
.Sh HISTORY
These functions appeared in
.Ox 2.0 .
.Sh AUTHORS
The original MD4 routines were developed by
.Tn RSA
Data Security, Inc., and published in the above references.
This code is derived from a public domain implementation written by Colin Plumb.
.Pp
The
.Fn MD4End ,
.Fn MD4File ,
.Fn MD4FileChunk ,
and
.Fn MD4Data
helper functions are derived from code written by Poul-Henning Kamp.
.Sh BUGS
Collisions have been found for the full versions of both MD4 and MD5.
The use of
.Xr sha2 3
is recommended instead.
